#port and name
spring.application.name=micro
server.port=8069

#url
spring.datasource.url=jdbc:mysql://localhost:3306/micro
#spring.datasource.url=jdbc:postgresql://localhost:5432/
#cred
spring.datasource.username=root
spring.datasource.password=root
#ddl
spring.jpa.hibernate.ddl-auto=update
